"""Golden parity: backend/app/engine.py must reproduce shared/golden/golden.json exactly.

The golden file is generated by shared/reference/gen-golden.mjs from the reference engine
(shared/reference/engine.mjs). The only allowed difference is report['engine']['runtime'].
Do not edit this file or the golden file to make a test pass: fix the engine.
"""
from __future__ import annotations

import copy
import json
import re

import pytest

from app import engine
from app.config import find_shared, load_config

GOLDEN = json.loads((find_shared() / 'golden' / 'golden.json').read_text(encoding='utf-8'))
CASES = GOLDEN['cases']


def _short(v, limit=200):
    s = repr(v) if isinstance(v, str) else json.dumps(v, ensure_ascii=False, default=repr)
    return s if len(s) <= limit else s[:limit] + '...'


def first_diff(got, exp, path='$'):
    """Describes the first difference between got and exp, or returns None. Booleans never equal numbers."""
    if isinstance(exp, bool) or isinstance(got, bool):
        if isinstance(exp, bool) and isinstance(got, bool) and exp == got:
            return None
        return f'{path}: expected {_short(exp)}, got {_short(got)}'
    if isinstance(exp, (int, float)) and isinstance(got, (int, float)):
        return None if got == exp else f'{path}: expected {exp!r}, got {got!r}'
    if isinstance(exp, dict):
        if not isinstance(got, dict):
            return f'{path}: expected an object, got {_short(got)}'
        missing = [k for k in exp if k not in got]
        extra = [k for k in got if k not in exp]
        if missing or extra:
            return f'{path}: missing keys {missing}, unexpected keys {extra}'
        for k in exp:
            d = first_diff(got[k], exp[k], f'{path}.{k}')
            if d:
                return d
        return None
    if isinstance(exp, list):
        if not isinstance(got, list):
            return f'{path}: expected a list, got {_short(got)}'
        if len(got) != len(exp):
            return f'{path}: expected {len(exp)} items, got {len(got)}: {_short(got)}'
        for i, (g, e) in enumerate(zip(got, exp)):
            d = first_diff(g, e, f'{path}[{i}]')
            if d:
                return d
        return None
    if type(got) is not type(exp) or got != exp:
        return f'{path}: expected {_short(exp)}, got {_short(got)}'
    return None


def _run(case, cfg):
    kind, inp = case['kind'], case['input']
    if kind == 'analyze':
        return engine.analyze(copy.deepcopy(inp), cfg, 'python')
    if kind == 'analyzeText':
        return engine.analyze_text(inp, cfg)
    if kind == 'analyzeUrl':
        return engine.analyze_url(inp, cfg)
    if kind == 'parseQr':
        return engine.parse_qr(inp, cfg)
    if kind == 'fmtINR':
        return engine.fmt_inr(inp)
    if kind == 'fnv1a':
        return engine.fnv1a(inp)
    raise AssertionError('unknown golden kind ' + kind)


def _case_id(c):
    return re.sub(r'\s+', '_', f"{c['kind']}:{c['name']}")[:70]


@pytest.mark.parametrize('case', CASES, ids=[_case_id(c) for c in CASES])
def test_golden(case):
    got = _run(case, load_config())
    exp = case['expected']
    if case['kind'] == 'analyze':
        assert got['engine']['runtime'] == 'python'
        got = {**got, 'engine': {**got['engine'], 'runtime': exp['engine']['runtime']}}
    diff = first_diff(got, exp)
    assert diff is None, diff


def test_engine_does_not_mutate_config():
    cfg = load_config()
    before = json.dumps(cfg, sort_keys=True)
    for case in CASES[:40]:
        _run(case, cfg)
    assert json.dumps(cfg, sort_keys=True) == before
